export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';
export const VIEW_PROFILE_REQUEST = 'VIEW_PROFILE_REQUEST';
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS';
export const VIEW_PROFILE_FAILED = 'VIEW_PROFILE_FAILED';
export const GET_UPLOADED_IMAGE = 'GET_UPLOADED_IMAGE';
export const SUCCESSFUL_IMAGE_UPLOAD = 'SUCCESSFUL_IMAGE_UPLOAD';
export const IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_FAILED';
