export const LIKE_SUCCESS="LIKE_SUCCESS";
export const LIKE_FAIL="LIKE_FAIL";
export const UNLIKE_SUCCESS="UNLIKE_SUCCESS";
export const UNLIKE_FAIL="UNLIKE_FAIL";
export const GET_LIKES="GET_LIKES";
export const GET_LIKES_FAIL="GET_LIKES_FAIL";
export const FETCH_LIKERS_SUCCESS="FETCH_LIKES_SUCCESS";
export const FETCH_LIKERS_FAIL="FETCH_LIKES_SUCCESS";
