// actions go here


export const RESET_PASSWORD = "RESET_ACCOUNT_PASSWORD";
export const FORM_SUBMIT = "SUBMIT_FORM_DATA";
export const SUBMIT_SUCCESSFUL = "SUBMIT_SUCCESSFUL";
export const SUBMIT_FAILED = "SUBMIT_FAILED";
export const VALIDATE_EMAIL = "VALIDATE_EMAIL";

export const SUBMIT_RESET_LINK = "SUBMIT_RESET_LINK";
export const SUBMIT_RESET_PASSWORD = "SUBMIT_RESET_PASSWORD";

export const NON_MATCHING_PASSWORD = "NON_MATCHING_PASSWORD";



