/* eslint-disable import/prefer-default-export */
export const FETCH_COMMENTS_REACTIONS = 'FETCH_COMMENTS_REACTIONS';
export const FETCH_COMMENTS_REACTIONS_FAILURE = 'FETCH_COMMENTS_REACTIONS_FAILURE';
export const ADD_COMMENT_REACTION = 'ADD_COMMENT_REACTION';
export const UNDO_COMMENT_REACTION = 'UNDO_COMMENT_REACTION';
export const ADD_COMMENT_REACTION_FAILURE = 'ADD_COMMENT_REACTION_FAILURE';
