export const GET_READ_NOTIFICATIONS = "GET_READ_NOTIFICATIONS";
export const GET_UNREAD_NOTIFICATIONS = "GET_UNREAD_NOTIFICATIONS";
export const GET_SPECIFIC_NOTIFICATION = "GET_SPECIFIC_NOTIFICATION";
export const MARK_AS_READ = "MARK_AS_READ";
export const MARK_AS_UNREAD = "MARK_AS_UNREAD";
export const FORM_SUBMIT = "SUBMIT_FORM_DATA";
export const FETCH_NOTIFICATIONS_SUCCESSFUL = "FETCH_NOTIFICATIONS_SUCCESSFUL";
export const FETCH_NOTIFICATIONS_FAILED = "FETCH_NOTIFICATIONS_FAILED";
